### ISSUE TITLE
Runs fail when a feature is not given a number of stories

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt-geojson-gem#107]
code to calculate shading from other buildings/district systems crashes the run when a DS does not have number of stories.  Fixing this to: 1) report a warning in run.log, and 2) throw out the feature from the shading calculations.

**Comment by kflemin** [comment]
@tanushree04, do you think this is appropriate, or would it be better to fail the run when one of the DS doesn't have a # of stories?

**Comment by tanushree04** [comment]
@kflemin , in case of detailed_model_filenames, we were issuing this message when a feature does not have the number of stories specified: https://github.com/urbanopt/urbanopt-geojson-gem/blob/b0957fbb0924dc94ac917ada0453aa91db23a34f/lib/urbanopt/geojson/geo_file.rb#L101

**Comment by kflemin** [comment]
True, but only for buildings.  District systems are also considered in shading calcs and there is no check for those features.  (the process_other_building function in helper.rb is crashing in that case).  I added code to skip that feature (building or ds) from the shading calculations when there is no #stories, but is that appropriate results-wise, or is it better to actually fail the runs?

**Comment by tanushree04** [comment]
@kflemin I think it would be appropriate to issue a warning and exclude that feature from the shading calculations, the same approach you're suggesting.
