### ISSUE TITLE
UO UI defaults fail schema validation

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-geojson-gem#271]
- [underground_cables_ratio](https://github.com/urbanopt/urbanopt-geojson-gem/blob/develop/lib/urbanopt/geojson/schema/site_properties.json#L78) is populated with `null` while the schema expects a `number`.
- [max_number_of_lv_nodes_per_building](https://github.com/urbanopt/urbanopt-geojson-gem/blob/develop/lib/urbanopt/geojson/schema/site_properties.json#L86) is populated with `null` while the schema expects a `number`.

I didn't use those keys in the UI, they got added when I exported the geojson feature file with `null` value.

The UI shouldn't generate an invalid file.

Potential solutions:
1. Manually deleting those keys from the feature file makes everything happy again (this doesn't feel like a solution)
2. Update validation/schema to accept `null` for those keys
3. Update UI to not include those keys in the exported geojson file if they aren't being used
4. Update UI to populate with a no-op value (not sure this is possible)
5. Something else?

**Comment by vtnate** [comment]
@kflemin Do you have a preference between choices 1-5?

**Comment by kflemin** [comment]
@vtnate

I like option 3!
