### ISSUE TITLE
urbanopt-geojson-gem doesn't work when run without gem repo checked out.

### ISSUE THREAD

**Issue by DavidGoldwasser** [urbanopt/urbanopt-geojson-gem#43]
requiring 'urbanopt/geojson` breaks the measure when used on OpenStudio Server.
https://github.com/urbanopt/urbanopt-geojson-gem/blob/develop/lib/measures/urban_geometry_creation/measure.rb#L34

If the files are not going to be in resources directory, then it should just require the gem, then I can pass the gem in as worker initialization script. Work around would be for me to copy elements of the gem into the analysis, but that isn't ideal.

**Comment by vtnate** [comment]
@DavidGoldwasser I ran into a similar issue once, and I think I solved it by adding `spec.add_dependency "urbanopt-geojson", "~> 0.1.0"` to the gemspec of the repo that was requiring the geojson gem. Hope that's helpful.

**Comment by nllong** [comment]
@DavidGoldwasser did nates suggest fix this for you?

**Comment by DavidGoldwasser** [comment]
@nllong I'll give this a try and see if that works. @vtnate did you just make this change on local copy, or do you have a branch I can check out with this change.

**Comment by kflemin** [comment]
you can use the develop branch.
- make sure you rake install the gem to get access to the CLI globally
- make sure you have  Gemfile in your project folder and that your bundle is getting sent to the openstudio call

**Comment by vtnate** [comment]
I just did it locally at the time. That being said, however, the CLI has been released on rubygems (urbanopt-cli) and should have that dependency included in it. I'd consider the CLI in beta phase right now. It works as expected for a limited number of uses, so if you're getting fancy I'm sure you can find things it doesn't yet do.

**Comment by kflemin** [comment]
I think this is resolved but reopen if not...
