### ISSUE TITLE
urban_geometry is creating inconsistent construction assignments to adiabatic floor and ceiling surfaces

### ISSUE THREAD

**Issue by DavidGoldwasser** [urbanopt/urbanopt-geojson-gem#89]
This was resulting in variation in simulation results most end uses (interior equipment and exterior lights) by up to 5% when re-running the same OSW multiple times. I tested runs with the OpenStudio CLI and using OpenStudio 2.9.1

The cause was here, where hard constructions are assigned and boundary conditions changed to adiabatic. I would have expected it to be wrong but in a consistent way, so I'll recommend two fixes. 

First, the main issue, this line
https://github.com/urbanopt/urbanopt-geojson-gem/blob/954a04495d1dc8bd9385796dc3701cbe56a80f17/lib/urbanopt/geojson/model.rb#L75

Should be moved to just above this line 
https://github.com/urbanopt/urbanopt-geojson-gem/blob/954a04495d1dc8bd9385796dc3701cbe56a80f17/lib/urbanopt/geojson/model.rb#L81

The reason for setting the boundary condition later is so that the line shown below here that gets the construction of the adjacent surface can run before the boundary condition of the adjacent surface is changed to `Outdoors` by the API when the primary surface is no longer connected by the `Surface` boundary condition.
https://github.com/urbanopt/urbanopt-geojson-gem/blob/954a04495d1dc8bd9385796dc3701cbe56a80f17/lib/urbanopt/geojson/model.rb#L77

Also just to provide a little more stability, when looping through surfaces, add `.sort` results are repeatable. `model.getSurfaces.sort.each do |surface|
https://github.com/urbanopt/urbanopt-geojson-gem/blob/954a04495d1dc8bd9385796dc3701cbe56a80f17/lib/urbanopt/geojson/model.rb#L68

**Comment by DavidGoldwasser** [comment]
Pre-fix results
<img width="1173" alt="Screen Shot 2020-05-18 at 3 44 14 PM" src="https://user-images.githubusercontent.com/4857055/82263071-5eb24a00-991f-11ea-87ce-b4169d330cd7.png">

Post-fix results
<img width="1163" alt="Screen Shot 2020-05-18 at 3 39 31 PM" src="https://user-images.githubusercontent.com/4857055/82263111-6eca2980-991f-11ea-840c-0e76178b7f43.png">

**Comment by DavidGoldwasser** [comment]
A long term fix is for openstudio-standards, the extension-gem and this to use the adiabatic field for default construction set. Unfortunately there is only a single field, not one for floor, roof, and walls. In other model articulation workflows (outside of urban_geometry measure) we also use adiabatic to represent party walls, but in those cases a hard coded construction could be applied.

Note: even for roof ceiling the default isn't ideal, if for example you have carpet on the floor, and want to represent that in the adiabatic default.

**Comment by kflemin** [comment]
let's make sure to add a test to prevent this in the future.

**Comment by DavidGoldwasser** [comment]
Test is good idea. Ideally we have a series of multi-repo workflow tests that run simulations and look at results; but if we want to write a measure test that just uses this repo we can create a seed model of the URBANopt workflow right after the blend measure. @tanushree04 a way to do that would be to set skip to true on all measure after blend and you can run it normally or with `--measures_only`.  Make that the seed for the measure. Then the measure test needs to run one or more simulations to look at the results, as it would be hard to pick this up on the input. Could save expected results from run now, and run the test once, or could run it multiple times (3-5) and confirm the results relative to each other.

The problem here, if we are just using this measure and repo, is we would have to run it without a mechanical system, or with ideal air loads thrown in (or something simple written in the measure test). I think in the end something more basic here and then multi-repo managed elsewhere might be best for this. Maybe in or alongside the example project repo>

**Comment by tanushree04** [comment]
I have added a test that loads in a model with a construction set assigned, it creates adiabatic surfaces for the model and hard assigns constructions, and checks whether the correct constructions were assigned from the construction set. 

https://github.com/urbanopt/urbanopt-geojson-gem/blob/edbe9ec3b4e0c741722d7eef9f9c669b34d9d6c5/spec/urbanopt/geojson/model_spec.rb#L62
